# name: Run Python Script
# on: [push]
# jobs:
#   run-python:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Set up python
#         name: action/setup-python@v4
#         with:
#           python-version: '3.11'
#       - name: Run Python Script
#         run: python app.py

name: Run Python Script

on:
  push:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python Script
        run: python app.py
